name: "CI (Integração Continua): Main Workflow"

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run npm install
              run: npm install
            - name: Run Linter
              run: npm run lint 
