name: "CI (Integração Continua): Primeira Action"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [opened, synchronizegit]
  
jobs:
  exemplo: # Job exemplo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #run echo
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Run a list file command
        run: ls -la
